### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by CandySz** [Uenhe/Fire#2]
For some reason, 'content' > "items" is missing, being impossible to play the mod.

**Comment by Uenhe** [comment]
it should be. the items are in 'scripts/items.js'.
notice that iOS devices are unable to play this mod.

**Comment by CandySz** [comment]
> it should be. the items are in 'scripts/items.js'. notice that iOS devices are unable to play this mod.

I play on a android, are you sure is there?
Even in github the items as missing
![20230716_153312](https://github.com/Uenhe/Fire/assets/137945005/d7692172-b3f1-4f83-9369-124b82ccac2e)

**Comment by Uenhe** [comment]
> > it should be. the items are in 'scripts/items.js'. notice that iOS devices are unable to play this mod.
> 
> I play on a android, are you sure is there? Even in github the items as missing ![20230716_153312](https://user-images.githubusercontent.com/137945005/253821107-d7692172-b3f1-4f83-9369-124b82ccac2e.png)

uhhhh.. if its impossible to play the mod, did the game crashed, said something failed to parse or something else?

**Comment by Uenhe** [comment]
here are items.
![QQ截图20230717082058](https://github.com/Uenhe/Fire/assets/119563256/197845dc-7706-45f0-ac54-eb17b6225465)
